services:
  react:
    build: ./Dog_Adoption_React
    hostname: react
    ports:
      - "5060:3000"
    expose:
      - 5060
    environment:
      - REACT_APP_API_BASE_URL=http://DogExpress:3000
    container_name: DogReact
    networks:
      - mynetwork
  
  express:
    build: ./Dog_Adoption_Express
    ports:
      - "5061:5000"
    environment:
      - PORT=5000
    container_name: DogExpress
    networks:
      - mynetwork
  
networks:
  mynetwork: